# application server port
server:
  port: 8181

# Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521
    username: hr
    password:

  #JPA Settings
  jpa:
    properties:
      hibernate.enable_lazy_load_no_trans: true
    database: oracle
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update
    show-sql: true