# application server port
server:
  port: 8181

# Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/QUIZ_PORTAL_TEST
    username: postgres
    password:

  jpa:
    properties:
      hibernate.enable_lazy_load_no_trans: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  #Enable Color in Spring Boot Console Log
  output:
    ansi:
      enabled: always