# application server port
server:
  port: 8181

# Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    driver-class-name: org.postgresql.Driver #oracle.jdbc.OracleDriver
    url: jdbc:postgresql://localhost:5432/QUIZ_PORTAL_TEST #jdbc:oracle:thin:@//localhost:1521
    username: ${PG_USERNAME} # hr -> for oracle db username
    password:

  #JPA Settings
  jpa:
    properties:
      hibernate.enable_lazy_load_no_trans: true
    database: postgresql #oracle
    database-platform:  org.hibernate.dialect.PostgreSQL94Dialect #org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update
    show-sql: true