# application server port
server:
  port: ${SPRING_PORT}

# Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/QUIZ_PORTAL_DEV
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}

  #JPA Settings
  jpa:
    properties:
      hibernate.enable_lazy_load_no_trans: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

  #Liquibase Config
  liquibase:
    contexts: dev
    enabled: false #we ignore it for dev.
    drop-first: false
    clear-checksums: true
    change-log: classpath:db/changelog/changelog-master.xml
