
 ----- USERS TABLE CREATE SCRIPT -----

CREATE TABLE "HR"."USERS"
(	"ID" NUMBER(19,0) NOT NULL ENABLE,
     "CREATED_BY" VARCHAR2(255 CHAR),
     "CREATED_DATE" TIMESTAMP (6),
     "LAST_MODIFIED_BY" VARCHAR2(255 CHAR),
     "LAST_MODIFIED_DATE" TIMESTAMP (6),
     "EMAIL" VARCHAR2(255 CHAR),
     "FIRST_NAME" VARCHAR2(255 CHAR),
     "LAST_NAME" VARCHAR2(255 CHAR),
     "PASSWORD" VARCHAR2(255 CHAR),
     "PHONE" VARCHAR2(255 CHAR),
     "USERNAME" VARCHAR2(255 CHAR),
     "PROFILE" VARCHAR2(255 CHAR),
     "RECORD_STATUS" NUMBER(10,0),
     "ENABLED" NUMBER(10,0),
     PRIMARY KEY ("ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
         BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "USERS"  ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

 ----- ROLES TABLE CREATE SCRIPT -----

 CREATE TABLE "HR"."ROLES"
 (	"ID" NUMBER(19,0) NOT NULL ENABLE,
      "CREATED_BY" VARCHAR2(255 CHAR),
      "CREATED_DATE" TIMESTAMP (6),
      "LAST_MODIFIED_BY" VARCHAR2(255 CHAR),
      "LAST_MODIFIED_DATE" TIMESTAMP (6),
      "ROLE_NAME" VARCHAR2(255 CHAR),
      "RECORD_STATUS" NUMBER(10,0),
      PRIMARY KEY ("ID")
          USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
          STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
          PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
          BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
          TABLESPACE "USERS"  ENABLE
 ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

----- USER_ROLE TABLE CREATE SCRIPT -----

 CREATE TABLE "HR"."USER_ROLE"
 (	"ID" NUMBER(19,0) NOT NULL ENABLE,
      "CREATED_BY" VARCHAR2(255 CHAR),
      "CREATED_DATE" TIMESTAMP (6),
      "LAST_MODIFIED_BY" VARCHAR2(255 CHAR),
      "LAST_MODIFIED_DATE" TIMESTAMP (6),
      "ROLE_ID" NUMBER(19,0),
      "USER_ID" NUMBER(19,0),
      "RECORD_STATUS" NUMBER(10,0),
      PRIMARY KEY ("ID")
          USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
          STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
          PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
          BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
          TABLESPACE "USERS"  ENABLE,
      CONSTRAINT "FKT7E7DJP752SQN6W22I6OCQY6Q" FOREIGN KEY ("ROLE_ID")
          REFERENCES "HR"."ROLES" ("ID") ENABLE,
      CONSTRAINT "FKJ345GK1BOVQVFAME88RCX7YYX" FOREIGN KEY ("USER_ID")
          REFERENCES "HR"."USERS" ("ID") ENABLE
 ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

